vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

local c = require("palettes.gruver16")
local hl = vim.api.nvim_set_hl

hl(0, "Normal",         { fg = c.base05, bg = c.base00 })
hl(0, "NormalFloat",    { fg = c.base05, bg = c.base00 })
hl(0, "FloatBorder",    { bg = c.base00 })
hl(0, "Cursor",         { fg = c.base00, bg = c.base05 })
hl(0, "CursorLine",     { bg = c.base01 })
hl(0, "CursorLineNr",   { fg = c.base06 })
hl(0, "LineNr",         { fg = c.base04 })
hl(0, "Visual",         { bg = c.base02 })
hl(0, "Search",         { fg = c.base00, bg = c.base0A })
hl(0, "StatusLine",     { fg = c.base05, bg = c.base01 })
hl(0, "VertSplit",      { fg = c.base02 })
hl(0, "WinSeparator",   { fg = c.base02, bg = c.base00 })
hl(0, "Pmenu",          { fg = c.base05, bg = c.base01 })
hl(0, "PmenuSel",       { fg = c.base00, bg = c.base0D })
hl(0, "YankHighlight",  { fg = c.base00, bg = c.base0E })
hl(0, "Directory",      { fg = c.base0D, bg = c.base00 })
hl(0, "MatchParen",     { bg = c.base03, bold = true })

hl(0, "Comment",        { fg = c.base04 })
hl(0, "Constant",       { fg = c.base09 })
hl(0, "String",         { fg = c.base0B })
hl(0, "Character",      { fg = c.base0B })
hl(0, "Number",         { fg = c.base09 })
hl(0, "Boolean",        { fg = c.base0C })
hl(0, "Identifier",     { fg = c.base05 })
hl(0, "Function",       { fg = c.base0D })
hl(0, "Statement",      { fg = c.base0E })
hl(0, "Keyword",        { fg = c.base0E })
hl(0, "Operator",       { fg = c.base05 })
hl(0, "PreProc",        { fg = c.base0A })
hl(0, "Type",           { fg = c.base0A })
hl(0, "Special",        { fg = c.base0A })
hl(0, "Underlined",     { fg = c.base0D, underline = true })
hl(0, "Error",          { fg = c.base08, bold = true })
hl(0, "Todo",           { fg = c.base00, bg = c.base08, bold = true })

hl(0, "@variable",               { fg = c.base05 })
hl(0, "@function",               { fg = c.base0D })
hl(0, "@keyword",                { fg = c.base0E })
hl(0, "@keyword.operator",       { fg = c.base0E })
hl(0, "@lsp.type.operator",      {})
hl(0, "@lsp.type.operator.cpp",  {})
hl(0, "@lsp.type.namespace.cpp", { fg = c.base0C })
hl(0, "@string",                 { fg = c.base0B })
hl(0, "@number",                 { fg = c.base09 })
hl(0, "@type",                   { fg = c.base0A })
hl(0, "@comment",                { fg = c.base04 })
hl(0, "@constant",               { fg = c.base0C })
hl(0, "@punctuation",            { fg = c.base09 })

hl(0, "FoldColumn",         { fg = c.base03, bg = "NONE" })
hl(0, "Folded",             { fg = c.base05, bg = c.base01 })
hl(0, "UfoFoldedBg",        { bg = c.base02 })
hl(0, "BlinkCmpMenu",       { bg = c.base00 })
hl(0, "BlinkCmpMenuBorder", { bg = c.base00 })
hl(0, "BlinkCmpDoc",        { bg = c.base00 })
hl(0, "BlinkCmpDocBorder",  { bg = c.base00 })

hl(0, 'cTypeQualifier',             { link = 'Keyword' })
hl(0, "cTypedef",                   { link = 'Keyword' })
hl(0, "cStructure",                 { link = 'Keyword' })
hl(0, "cppStatement",               { link = 'Keyword' })
hl(0, "@punctuation.delimiter.cpp", { fg = c.base05 })

hl(0, "GitSignsAdd",    { bg = c.base00, fg = c.base0B, bold = false })
hl(0, "GitSignsDelete", { bg = c.base00, fg = c.base08, bold = false })
hl(0, "GitSignsChange", { bg = c.base00, fg = c.base0E, bold = false })
