vim.api.nvim_set_hl(0, 'MatchParen', {fg = '#ffffff', bg = '#484848'})
vim.api.nvim_set_hl(0, 'NormalFloat', {fg = '#ffffff', bg = '#181818'})
vim.api.nvim_set_hl(0, 'BlinkCmpGhostText', {fg = '#686868', bg = '#282828'})
vim.api.nvim_set_hl(0, '@property.cpp', {link = 'GruberDarkerQuartz'})
vim.api.nvim_set_hl(0, '@property.c', {link = 'GruberDarkerQuartz'})
